name: Build
on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  release:
    types: [ published ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: namespace-profile-linux-default
    steps:
      - uses: namespacelabs/nscloud-checkout-action@v9
      - name: Set up cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: gradle

      - name: Setup gradle build cache
        run: |
          nsc cache gradle setup --init-gradle /tmp/init.gradle

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true # namespace handles this

      - name: "setup java"
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: 25
          cache: "" # namespace handles this

      - name: Build
        run: ./gradlew --init-script=/tmp/init.gradle build --stacktrace
      - name: Determine Status
        run: |
          if [ "$(./gradlew --init-script=/tmp/init.gradle properties | awk '/^version:/ { print $2; }' | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> $GITHUB_ENV
          else
            echo "STATUS=release" >> $GITHUB_ENV
          fi
      - name: Publish Snapshot
        if: "${{ env.STATUS != 'release' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}"
        run: ./gradlew --init-script=/tmp/init.gradle publish
        env:
          ORG_GRADLE_PROJECT_paperSnapshotsUsername: "${{ secrets.ARTIFACTORY_USERNAME }}"
          ORG_GRADLE_PROJECT_paperSnapshotsPassword: "${{ secrets.ARTIFACTORY_PASSWORD }}"
      - name: Publish Release
        if: "${{ env.STATUS == 'release' && github.event_name == 'release' }}"
        run: ./gradlew --init-script=/tmp/init.gradle publish
        env:
          ORG_GRADLE_PROJECT_paperReleasesUsername: "${{ secrets.ARTIFACTORY_USERNAME }}"
          ORG_GRADLE_PROJECT_paperReleasesPassword: "${{ secrets.ARTIFACTORY_PASSWORD }}"
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.SIGNING_PASSWORD }}"
